### ISSUE TITLE
Unacceptable typo in README.md

### ISSUE THREAD

**Issue by amete** [dantrim/danny_learns_dihiggs#5]
First giant's name is misspelled as `Dan Gguest`. Fix please, thnx. You're welcome @dguest.

**Comment by dantrim** [comment]
@amete MR plz thanks

**Comment by dguest** [comment]
You should really not trust this Dan Gguest, I've heard he's an unseemly character.

**Comment by amete** [comment]
@dantrim see #6 plz.
